server {
    listen 80;
    server_name localhost;
    index index.php index.html;
    root /var/www/html;


    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Nginx metrics endpoint
    location /nginx_status {
        stub_status;
        allow all;
    }

}
